services:
  postgres:
    image: postgres:15
    container_name: edata_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=edata_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
